/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2019-04-02 10:55:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.franchisee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(14);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1551882069000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar!/META-INF/taglib.tld", Long.valueOf(1539665194000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar", Long.valueOf(1551882067000L));
    _jspx_dependants.put("/WEB-INF/tlds/function.tld", Long.valueOf(1551597161000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar", Long.valueOf(1551882069000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/head.jspf", Long.valueOf(1554084461000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/spring-modules-validation-0.9.jar!/META-INF/spring-commons-validator.tld", Long.valueOf(1204779052000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/declare.jspf", Long.valueOf(1554084461000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-modules-validation-0.9.jar", Long.valueOf(1551882069000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

        pageContext.setAttribute("crlf", "\r\n");
        pageContext.setAttribute("lf", "\n");
        pageContext.setAttribute("cr", "\r");

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<title>로그인 | 포메인 가맹점 관리</title>\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

        pageContext.setAttribute("crlf", "\r\n");
        pageContext.setAttribute("lf", "\n");
        pageContext.setAttribute("cr", "\r");

      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/asset/images/common/favicon.ico\">\r\n");
      out.write("<link rel=\"icon\" href=\"/asset/images/common/favicon.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/asset/common/css/style.css\" media=\"all\">\r\n");
      out.write("<!--[if lte IE 8]>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../common/css/ie8.css\" media=\"all\">\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"/asset/common/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script src=\"/asset/common/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"/asset/common/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"/asset/common/js/jquery.form.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/editor/js/HuskyEZCreator.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"/asset/common/js/check.js\"></script>\r\n");
      out.write("<script src=\"/asset/common/js/common.js\"></script>\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/asset/common/css/ie9.css\" media=\"all\">\r\n");
      out.write("\t<script src=\"/asset/common/js/placeholders.min.js\"></script>\r\n");
      out.write("\t<script src=\"/asset/common/js/html5.js\"></script>\r\n");
      out.write("<![endif]-->");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- wrap -->\n");
      out.write("<div id=\"wrap\">\n");
      out.write("\n");
      out.write("\t<!-- login-wrap -->\n");
      out.write("\t<div class=\"login-wrap\">\n");
      out.write("\t\t<div class=\"d-t\">\n");
      out.write("\t\t\t<div class=\"d-c\">\n");
      out.write("\t\t\t\t<div class=\"input-data\">\n");
      out.write("\t\t\t\t\t<form action=\"./loginProc.do\" method=\"post\" name=\"loginForm\" onsubmit=\"return false;\">\n");
      out.write("\t\t\t\t\t<h1>포메인 가맹점 관리자 로그인</h1>\n");
      out.write("\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t<legend>로그인 입력 폼</legend>\n");
      out.write("\t\t\t\t\t\t<p class=\"input-cell\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"fId\" id=\"fId\" placeholder=\"\" data-null=\"not\" style=\"width:100%;\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"pu-id\">아이디</label>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"input-cell\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"fPw\" id=\"fPw\" placeholder=\"\" data-null=\"not\" style=\"width:100%;\" onKeyPress=\"if(event.keyCode == 13) { fnDoLogin(); return false; }\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"pu-pw\">비밀번호</label>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<div class=\"check-save\">\n");
      out.write("\t\t\t\t\t\t\t<p class=\"check-type01\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"save\" name=\"idsave\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"save\"><span></span>아이디 저장</label>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<p class=\"btn-login\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn-01 type-01\" onclick=\"javascript:fnDoLogin(); return false;\">로그인</button>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li>관리자로 로그인 하시려면 아이디와 비밀번호를 입력 해 주세요</li>\n");
      out.write("<!-- \t\t\t\t\t\t<li>관리자 계정 문의 및 비밀번호 변경은 데일리킹 <br>(Tel. 000-000-0000)로 문의바랍니다</li> -->\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<div class=\"copy\">\n");
      out.write("\t\t\t\t\t\t<p>경기도 성남시 분당구 황새울로 216, 401호 (수내동, 휴맥스빌리지) 주식회사 데일리킹 <br>Tel: 1899-2422 상호명: 주식회사 데일리킹<span>사업자등록번호: 129-86-03729</span></p>\n");
      out.write("\t\t\t\t\t\t<p>Copyright ⓒ 2018 DAILYKING INC. All rights reserved.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- //login-wrap -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- //wrap -->\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction fnDoLogin(){\n");
      out.write("\t\t\n");
      out.write("\t\tvar frm = $(\"form[name=loginForm]\");\t\t\n");
      out.write("\t\n");
      out.write("\t\tfrm.find(\"input[name='fId']\").val( $.trim(frm.find(\"input[name='fId']\").val()) );\n");
      out.write("\t\tfrm.find(\"input[name='fPw']\").val( $.trim(frm.find(\"input[name='fPw']\").val()) );\n");
      out.write("\t\t\n");
      out.write("\t\tif ( frm.find(\"input[name='fId']\").val() == '' ){\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요.\");\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\tif ( frm.find(\"input[name='fPw']\").val() == '' ){\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요.\");\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif (document.loginForm.idsave.checked == true) { // 아이디 저장을 체크 하였을때\n");
      out.write("            setCookie(\"adminid\", frm.find(\"input[name='fId']\").val(), 30); //쿠키이름을 id로 아이디입력필드값을 30일동안 저장\n");
      out.write("        } else { // 아이디 저장을 체크 하지 않았을때\n");
      out.write("            setCookie(\"adminid\", frm.find(\"input[name='fId']\").val(), 0); //날짜를 0으로 저장하여 쿠키삭제\n");
      out.write("        }\n");
      out.write("\t\t\n");
      out.write("        // ajaxSubmit 전 처리 작업\n");
      out.write("        var fnApplyBefore = function(romData, jqFrom, options){\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("        // ajaxSubmit 통신 후 처리 작업\n");
      out.write("        var fnApplyCallback = function(objResponse, statusText, xhr, $from){\n");
      out.write("        \tvar obj = JSON.parse( objResponse );\n");
      out.write("        \tif (statusText == \"success\"){\n");
      out.write("                if( obj[\"result\"] == 'S' ){\n");
      out.write("               \t\t//location.replace(\"/admin/menu/product_list.do\");\n");
      out.write("               \t\t//alert( obj[\"permission\"] );\n");
      out.write("                \t//location.replace(\"/admin/intranet/order_design_manage_list.do\");\n");
      out.write("               \t\tvar perArr = obj[\"permission\"].split(\",\");\n");
      out.write("               \t\t//alert( perArr.length );\n");
      out.write("               \t\tvar menuCd = perArr[0];\n");
      out.write("               \t\tif ( menuCd == '999' ) menuCd = perArr[1];\n");
      out.write("                \t//<![CDATA[\n");
      out.write("               \t\tlocation.replace(\"/store/intranet/board_list.do\");\n");
      out.write("                \t//]]>\n");
      out.write("                }else if(obj[\"result\"] == \"F\"){\n");
      out.write("                \talert(\"등록된 관리자 정보가 없습니다.\");\n");
      out.write("                }else{\n");
      out.write("                \talert(\"로그인 오류. \\n데이터 전송 중 오류가 발생하였습니다.\");                    \n");
      out.write("                }\n");
      out.write("            }else{\n");
      out.write("                alert(\"데이터 전송 중 오류가 발생하였습니다.\");    \n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        var options = {\n");
      out.write("            url : \"./loginProc.do\",\n");
      out.write("            type : \"post\" , \n");
      out.write("            dataType : 'json', \n");
      out.write("            beforeSerialize: function() {\n");
      out.write("\n");
      out.write("            },\n");
      out.write("            beforeSubmit : fnApplyBefore ,\n");
      out.write("            success : fnApplyCallback , \n");
      out.write("            error: function(data, result, resultMsg) {\n");
      out.write("            \t// console.dir(\"error : \" + result + \" [\"+ resultMsg + \"]\");\n");
      out.write("            }            \n");
      out.write("        };\n");
      out.write("        \n");
      out.write("       frm.ajaxSubmit( options );\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction setCookie(name, value, expiredays) //쿠키 저장함수\n");
      out.write("    {\n");
      out.write("        var todayDate = new Date();\n");
      out.write("        todayDate.setDate(todayDate.getDate() + expiredays);\n");
      out.write("        document.cookie = name + \"=\" + escape(value) + \"; path=/; expires=\"\n");
      out.write("                + todayDate.toGMTString() + \";\"\n");
      out.write("    }\n");
      out.write(" \n");
      out.write("    function getCookie(Name) { // 쿠키 불러오는 함수\n");
      out.write("        var search = Name + \"=\";\n");
      out.write("        if (document.cookie.length > 0) { // if there are any cookies\n");
      out.write("            offset = document.cookie.indexOf(search);\n");
      out.write("            if (offset != -1) { // if cookie exists\n");
      out.write("                offset += search.length; // set index of beginning of value\n");
      out.write("                end = document.cookie.indexOf(\";\", offset); // set index of end of cookie value\n");
      out.write("                if (end == -1)\n");
      out.write("                    end = document.cookie.length;\n");
      out.write("                return unescape(document.cookie.substring(offset, end));\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\t    \n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t if (getCookie(\"adminid\")) { // getCookie함수로 id라는 이름의 쿠키를 불러와서 있을경우\n");
      out.write("            document.loginForm.fId.value = getCookie(\"adminid\"); //input 이름이 id인곳에 getCookie(\"id\")값을 넣어줌\n");
      out.write("            document.loginForm.idsave.checked = true; // 체크는 체크됨으로\n");
      out.write("        }\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("<script src=\"/asset/common/js/front_ui.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("domain");
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("requrl");
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("domain");
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("requrl");
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }
}
