/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2019-02-28 01:46:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.brand.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(15);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1551285793000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar!/META-INF/taglib.tld", Long.valueOf(1539665194000L));
    _jspx_dependants.put("/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar", Long.valueOf(1551285791000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("/WEB-INF/tlds/function.tld", Long.valueOf(1551285793000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/jsp/brand/include/brandheader.jsp", Long.valueOf(1551286983000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar", Long.valueOf(1551285793000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/spring-modules-validation-0.9.jar!/META-INF/spring-commons-validator.tld", Long.valueOf(1204779052000L));
    _jspx_dependants.put("/WEB-INF/jsp/brand/include/head.jspf", Long.valueOf(1551286983000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/declare.jspf", Long.valueOf(1551286982000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-modules-validation-0.9.jar", Long.valueOf(1551285792000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("jar:file:/www/dailyking_gabia_io/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

        pageContext.setAttribute("crlf", "\r\n");
        pageContext.setAttribute("lf", "\n");
        pageContext.setAttribute("cr", "\r");

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>브랜드 소개 | 포메인</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"Description\" content=\"쌀국수는 포메인! 한국식 베트남 쌀국수 전문점. 쌀국수, 월남쌈 등 메뉴 소개, 가맹점 개설 안내.\">\r\n");
      out.write("<meta name=\"Author\" content=\"만든이\">\r\n");
      out.write("<meta name=\"Keywords\" content=\"키워드\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta property=\"og:title\" content=\"포메인\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:url\" content=\"http://www.phomein.com\">\r\n");
      out.write("<meta property=\"og:image\" content=\"http://www.phomein.com/common/images/logo.gif\">\r\n");
      out.write("<meta property=\"og:description\" content=\"쌀국수는 포메인! 한국식 베트남 쌀국수 전문점. 쌀국수, 월남쌈 등 메뉴 소개, 가맹점 개설 안내.\">\r\n");
      out.write("<link rel=\"canonical\" href=\"http://www.phomein.com/m/\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../images/common/favicon.ico?v=1\">\r\n");
      out.write("<link rel=\"icon\" href=\"/brand/images/common/favicon.png?v=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/brand/common/css/style.css\" media=\"all\">\r\n");
      out.write("<script src=\"/brand/common/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"/brand/common/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"/brand/common/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"/brand/common/js/swiper.min.js\"></script>\r\n");
      out.write("<script src=\"/brand/common/js/slick.js\"></script>\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("\t<script src=\"../common/js/placeholders.min.js\"></script>\r\n");
      out.write("\t<script src=\"../common/js/html5.js\"></script>\r\n");
      out.write("<![endif]-->");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- skip-link -->\r\n");
      out.write("<a href=\"#dBody\" id=\"skip-link\">본문 바로가기</a>\r\n");
      out.write("<!-- //skip-link -->\r\n");
      out.write("\r\n");
      out.write("<!-- wrap -->\r\n");
      out.write("<div id=\"wrap\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- dHead -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<header id=\"dHead\">\r\n");
      out.write("\t\t<!-- header_wrap -->\r\n");
      out.write("\t\t<div class=\"header-wrap\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<h1><a href=\"/brand/main/\">PHOMEIN</a></h1>\r\n");
      out.write("\t\t\t\t<nav id=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">PHOMEIN</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/phomein/about.do\">브랜드 소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/phomein/phoever.do\">CSR</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/phomein/member_ship.do\">멤버십</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/phomein/mileage_01.do\">멤버십</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/phomein/mileage_02.do\">멤버십</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/phomein/mileage_03.do\">멤버십</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/phomein/mileage_04.do\">멤버십</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/phomein/coupon_01.do\">상품권</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/phomein/coupon_02.do\">상품권</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/phomein/coupon_03.do\">상품권</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">MENU</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/menu/menu_list.do\">메뉴소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">STORE</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/store/store_best.do\">2018 모범매장</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/store/store_list.do\">매장찾기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">COMMUNITY</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/community/notice/community_list.do\">공지 & 언론보도</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/community/event/community_list.do\">EVENT</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/brand/community/sns/community_list.do\">SNS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/community/notice/community_view.do\">공지 & 언론보도</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/community/event/community_view.do\">EVENT</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/brand/community/sns/community_view.do\">SNS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<div class=\"btn-franchisee\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">가맹점 모집</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btn-system\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">포메인 시스템</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //header_wrap -->\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\t\tvar url = $(location).attr(\"pathname\");\r\n");
      out.write("\t\t$(\"#gnb\" ).each(function( index ) {\r\n");
      out.write("\t\t\t$(this).find('ul li a').each(function(index) {\r\n");
      out.write("\t\t\t\tif($(this).attr(\"href\") == url){\r\n");
      out.write("\t\t\t\t\tvar $this = $(this);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($(this).parent(\"li\").css(\"display\") == \"none\") {\r\n");
      out.write("\t\t\t\t\t\tvar $text = $(this).text();\r\n");
      out.write("\t\t\t\t\t\t$(this).parent(\"li\").parent(\"ul\").find(\"li a\").each(function(index) {\r\n");
      out.write("\t\t\t\t\t\t\tif($text == $(this).text()) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).parent(\"li\").attr(\"class\", \"actived\");\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$this.parent(\"li\").attr(\"class\", \"actived\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\t<!--// dHead -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- dBody -->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\t00. main\t\t\t\t\t:\t메인\r\n");
      out.write("\t\t01. phomein\t\t\t\t\t:\t포메인\r\n");
      out.write("\t\t02. menu\t\t\t\t\t:\t메뉴\r\n");
      out.write("\t\t03. store\t\t\t\t\t:\t매장안내\r\n");
      out.write("\t\t04. community\t\t\t\t:\t커뮤니티\r\n");
      out.write("\t\t05. cs_center\t\t\t\t:\t고객의 소리\r\n");
      out.write("\t\t06. etc\t\t\t\t\t\t:\t푸터 컨텐츠\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"dBody\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- full-page -->\r\n");
      out.write("\t\t<div class=\"full-page\">\r\n");
      out.write("\t\t\t<div id=\"fullpage\">\r\n");
      out.write("\t\t\t\t<!-- section 1 -->\r\n");
      out.write("\t\t\t\t<div id=\"section1\" class=\"section\">\r\n");
      out.write("\t\t\t\t\t<div class=\"top-visual\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list\" style=\"background-image:url('../images/tmp/main_visual_01.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tit\">쌀국수는 포메인</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt\">The World’s Best Korean Vietnamese Restaurant Phomein</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list\" style=\"background-image:url('../images/tmp/main_visual_01_02.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tit\">쌀 한 톨부터 다른 포메인다움</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt\">햅쌀로 직접 만든 쌀국수면으로 깨끗하고 건강한 쌀국수를 선사합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list\" style=\"background-image:url('../images/tmp/main_visual_01.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tit\">매일매일 까다로운 포메인다움</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt\">The World’s Best Korean Vietnamese Restaurant Phomein</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list\" style=\"background-image:url('../images/tmp/main_visual_01_02.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tit\">재료부터 건강한 포메인다움</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt\">햅쌀로 직접 만든 쌀국수면으로 깨끗하고 건강한 쌀국수를 선사합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //section 1 -->\r\n");
      out.write("\t\t\t\t<!-- section 2 -->\r\n");
      out.write("\t\t\t\t<div id=\"section2\" class=\"section\" style=\"background-image:url('../images/tmp/main_visual_02.jpg');\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sales-volume\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"label\">Since 2006</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit\">대한민국 쌀국수의 역사, <br>포메인으로부터.</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"volume-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"volume\">144,540,000</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"txt\">쌀국수 누적 판매량</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"../images/icon/ico_sales_volume.png\" alt=\"\"/></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //section 2 -->\r\n");
      out.write("\t\t\t\t<!-- section 3 -->\r\n");
      out.write("\t\t\t\t<div id=\"section3\" class=\"section\" style=\"background-image:url('../images/tmp/main_visual_03.jpg');\">\r\n");
      out.write("\t\t\t\t\t<div class=\"menu-section\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"tit\">베트남 요리,<span>31가지 감동을 담다.</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t<p><a href=\"/brand/menu/menu_list.do\" class=\"btn\">포메인 전체메뉴 보기</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"txt\">* 매장별로 판매 메뉴는 상이 할 수 있습니다.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"img\"><img src=\"../images/icon/ico_menu_info_01.png\" alt=\"\"/></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"data\"><span class=\"volume2\">12</span><strong>th</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"txt\">SINCE 2006</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"img\"><img src=\"../images/icon/ico_menu_info_02.png\" alt=\"\"/></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"data\"><span class=\"volume2\">136</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"txt\">매장 수</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"img\"><img src=\"../images/icon/ico_menu_info_03.png\" alt=\"\"/></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"data\"><span class=\"volume2\">805</span><strong>억</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"txt\">매출액</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //section 3 -->\r\n");
      out.write("\t\t\t\t<!-- section 4 -->\r\n");
      out.write("\t\t\t\t<div id=\"section4\" class=\"section\" style=\"background-image:url('../images/tmp/main_visual_04.jpg');\">\r\n");
      out.write("\t\t\t\t\t<div class=\"service-section\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"tit\">당신의 모든 순간<span>포메인</span></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"img01\"><img src=\"../images/icon/ico_phone_01.png\" alt=\"\"/></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"img02\"><img src=\"../images/icon/ico_phone_02.png\" alt=\"\"/></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt\">포메인 <strong>카카오톡 선물하기</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"img01\"><img src=\"../images/icon/ico_moto_01.png\" alt=\"\"/></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"img02\"><img src=\"../images/icon/ico_moto_02.png\" alt=\"\"/></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"img03\"><img src=\"../images/icon/ico_moto_03.png\" alt=\"\"/></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"txt\">포메인 <strong>딜리버리 매장</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //section 4 -->\r\n");
      out.write("\t\t\t\t<!-- section 5 -->\r\n");
      out.write("\t\t\t\t<div id=\"section5\" class=\"section\" style=\"background-image:url('../images/tmp/main_visual_05.jpg');\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sns-section\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"tit\">PHOMEIN<span>SNS</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"img\"><img src=\"../images/icon/ico_Instagram_sns.png\" alt=\"\"/></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"../images/tmp/@img_190x190.jpg\" alt=\"\"/></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"../images/tmp/@img_190x190.jpg\" alt=\"\"/></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"../images/tmp/@img_190x190.jpg\" alt=\"\"/></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"../images/tmp/@img_190x190.jpg\" alt=\"\"/></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"../images/tmp/@img_190x190.jpg\" alt=\"\"/></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"../images/tmp/@img_190x190.jpg\" alt=\"\"/></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //section 5 -->\r\n");
      out.write("\t\t\t\t<!-- section 6 -->\r\n");
      out.write("\t\t\t\t<div id=\"section6\" class=\"section\" style=\"background-image:url('../images/tmp/main_visual_06.jpg');\">\r\n");
      out.write("\t\t\t\t\t<div class=\"commuity-section\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"news-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label\">NEWS</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\"><span>2018.02.26</span>포메인, 분짜의 역사를 다시 쓰다 '진.짜.분.짜' 출시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\"><span>2018.02.26</span>포메인, 분짜의 역사를 다시 쓰다 '진.짜.분.짜' 출시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\"><span>2018.02.26</span>포메인, 분짜의 역사를 다시 쓰다 '진.짜.분.짜' 출시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\"><span>2018.02.26</span>포메인, 분짜의 역사를 다시 쓰다 '진.짜.분.짜' 출시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom-box\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"event-box\" style=\"background-image:url('../images/tmp/@img_main_event.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label\">EVENT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"tit\">포메인과 함께 하는 <br>틀린그림 찾기!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"franchisee-box\" style=\"background-image:url('../images/content/main_franchisee.jpg');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label\">FRANCHISE</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"img\"><img src=\"../images/content/main_franchisee_02.png\" alt=\"phomein\"/></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"tit\">가맹 문의하러 가기</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"txt\">대표번호 : 1899-2422(연결 1)  /  031-780-1500 (직통) <br>이메일 : help@phomein.com</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //section 6 -->\r\n");
      out.write("\t\t\t\t<!-- section 7 -->\r\n");
      out.write("\t\t\t\t<div id=\"section7\" class=\"section fp-auto-height\">\r\n");
      out.write("\t\t\t\t\t<!-- dFoot -->\r\n");
      out.write("\t\t\t\t\t<footer id=\"dFoot\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- footer-menu -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"em\"><a href=\"#\">개인정보 취급방침</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">이메일 무단 수집 거부</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">(주)데일리킹</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">포메인 지원시스템</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"\"><a href=\"#\">마일리지 조회</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"\"><a href=\"#\">마일리지 통합</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"\"><a href=\"#\">상품권 구매</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ..footer-menu -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- family-site -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"family-site\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Family Site</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">사이트 1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">사이트 2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">사이트 3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- //family-site -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- corp-info -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"corp-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"info\"><span>상호 : 주식화사 데일리킹</span>주소 : 경기도 성남시 분당구 황새울로 216, 401호 (수내동, 휴맥스빌리지)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"info\"><span>대표전호 : 1899-2422</span>사업자등록번호 : 129-86-03729</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"corp\">ⓒ 2017 DALYKING INC. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- corp-info -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- sns -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"ico-f\"><a href=\"#\"><span>페이스북</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"ico-i\"><a href=\"#\"><span>인스타그램</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"ico-b\"><a href=\"#\"><span>블로그</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"ico-p\"><a href=\"#\"><span>페이스북</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- //sns -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t<!--// dFoot -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //section 7 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"quick-nav\">\r\n");
      out.write("\t\t\t\t<div class=\"right-nav\">\r\n");
      out.write("\t\t\t\t\t<div class=\"nav\" data-menuanchor=\"firstPage\"><a href=\"#firstPage\"><span>home</span></a></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav\" data-menuanchor=\"secondPage\"><a href=\"#secondPage\"><span>브랜드</span></a></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav\" data-menuanchor=\"thirdPage\"><a href=\"#thirdPage\"><span>메뉴</span></a></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav\" data-menuanchor=\"fourthPage\"><a href=\"#fourthPage\"><span>서비스</span></a></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav\" data-menuanchor=\"fifthPage\"><a href=\"#fifthPage\"><span>SNS</span></a></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"nav\" data-menuanchor=\"sixthPage\"><a href=\"#sixthPage\"><span>커뮤니티</span></a></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"icon-scroll\">\r\n");
      out.write("\t\t\t\t\t<p class=\"ico\"><img src=\"../images/icon/icon_mouse.png\" alt=\"마우스 아이콘\"></p>\r\n");
      out.write("\t\t\t\t\t<p><img src=\"../images/icon/icon_mouse_scroll.png\" alt=\"SCROLL\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //full-page -->\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--// dBody -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrap -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"../common/js/front_ui.js\"></script>\r\n");
      out.write("<script src=\"../common/js/jquery.fullpage.js\"></script>\r\n");
      out.write("<script src=\"http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"../common/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t// 메인 풀페이지\r\n");
      out.write("\t $(document).ready(function() {\r\n");
      out.write("\t\t$('#fullpage').fullpage({\r\n");
      out.write("\t\t\tanchors:['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'fifthPage', 'sixthPage'],\r\n");
      out.write("\t\t\tmenu: '.right-nav',\r\n");
      out.write("\t\t\tafterLoad: function(anchorLink, index){\r\n");
      out.write("\t\t\t\tif(index == 2){\r\n");
      out.write("\t\t\t\t\t$('.volume').counterUp({delay: 10,time: 500});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(index == 3){\r\n");
      out.write("\t\t\t\t\t$('.volume2').counterUp({delay: 10,time: 500});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//첫 페이지 슬라이드\r\n");
      out.write(" \tvar winW = $(window).width(),\r\n");
      out.write("\t\twinH = $(window).height(),\r\n");
      out.write("\t\ttopVisual = $('.top-visual'),\r\n");
      out.write("\t\tlist = topVisual.find('.list');\r\n");
      out.write("\r\n");
      out.write("\tlist.css({width: winW+'px', height: winH+'px'});\r\n");
      out.write("\r\n");
      out.write(" \ttopVisual.slick({\r\n");
      out.write("\t\tarrows: false,\r\n");
      out.write("\t\tdots: true,\r\n");
      out.write("\t\tcustomPaging: function(slider, i) {\r\n");
      out.write("\t\t\tvar tit = $(slider.$slides[i]).find('.tit').html();\r\n");
      out.write("\t\t\treturn '<div class=\"pager-tit\" class=' + i + '>'+ tit + '</div>';\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tfade: true,\r\n");
      out.write("\t\tslidesToShow: 1,\r\n");
      out.write("\t\tautoplay: true,\r\n");
      out.write("\t\tautoplaySpeed: 3000,\r\n");
      out.write("\t\tpauseOnHover:false,\r\n");
      out.write("\t\tpauseOnFocus:false\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write(" \t//ie 모션 생략\r\n");
      out.write("\tvar agt = navigator.userAgent.toLowerCase();\r\n");
      out.write("\tfunction msieScroll(){\r\n");
      out.write("\t\tif(agt.indexOf('msie 9.0') > -1){\r\n");
      out.write("\t\t\t$('.section').addClass('on');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tmsieScroll();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("domain");
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("requrl");
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
