/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2021-02-17 10:43:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.mbrand.etc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class terms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(18);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1551882069000L));
    _jspx_dependants.put("/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar", Long.valueOf(1551882067000L));
    _jspx_dependants.put("/WEB-INF/jsp/mbrand/include/brandheader.jsp", Long.valueOf(1585818424000L));
    _jspx_dependants.put("/WEB-INF/tlds/function.tld", Long.valueOf(1551597161000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar", Long.valueOf(1551882069000L));
    _jspx_dependants.put("jar:file:/www/phomein_com/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/www/phomein_com/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/jsp/mbrand/include/brandgnb.jsp", Long.valueOf(1612931711000L));
    _jspx_dependants.put("jar:file:/www/phomein_com/www/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("jar:file:/www/phomein_com/www/WEB-INF/lib/spring-modules-validation-0.9.jar!/META-INF/spring-commons-validator.tld", Long.valueOf(1204779052000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/declare.jspf", Long.valueOf(1558589614000L));
    _jspx_dependants.put("jar:file:/www/phomein_com/www/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar!/META-INF/taglib.tld", Long.valueOf(1539665194000L));
    _jspx_dependants.put("jar:file:/www/phomein_com/www/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-modules-validation-0.9.jar", Long.valueOf(1551882069000L));
    _jspx_dependants.put("jar:file:/www/phomein_com/www/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("/WEB-INF/jsp/mbrand/include/brandlnb.jsp", Long.valueOf(1612400361000L));
    _jspx_dependants.put("/WEB-INF/jsp/mbrand/include/brandfooter.jsp", Long.valueOf(1558589646000L));
    _jspx_dependants.put("/WEB-INF/jsp/mbrand/include/head.jspf", Long.valueOf(1558589647000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

        pageContext.setAttribute("crlf", "\r\n");
        pageContext.setAttribute("lf", "\n");
        pageContext.setAttribute("cr", "\r");

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\">\n");
      out.write("<meta name=\"keywords\" content=\"\">\n");
      out.write("<title>포메인</title>\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mbrand/common/css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mbrand/common/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mbrand/common/css/layout.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mbrand/common/css/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mbrand/common/css/jquery.fullpage.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mbrand/common/css/main.css\">\r\n");
      out.write("<!-- 20190319 추가 s -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/mbrand/common/css/jquery-ui.css\">\r\n");
      out.write("<!-- //20190319 추가 e -->\r\n");
      out.write("<script src=\"/mbrand/common/js/jquery.js\"></script>\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"../common/js/placeholders.min.js\"></script>\r\n");
      out.write("\t<script src=\"../common/js/html5shiv.js\"></script>\r\n");
      out.write("<![endif]--> \r\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<!-- wrap -->\n");
      out.write("<div id=\"wrap\">\n");
      out.write("\t<!-- skip nav -->\n");
      out.write("\t<div id=\"skip_nav\">\n");
      out.write("        <a href=\"#content\">본문 바로가기</a>\n");
      out.write("    </div>\n");
      out.write("    <!-- //skip nav -->\n");
      out.write("\n");
      out.write("\t<!-- header -->\n");
      out.write("\t");
      out.write("\n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<h1>\n");
      out.write("\t\t\t<a href=\"/mbrand/main/main.do\"><span class=\"blind\">포메인</span></a>\n");
      out.write("\t\t</h1>\n");
      out.write("\t\t<div class=\"link\">\n");
      out.write("\t\t\t<a href=\"/mcompany/main/main.do\" class=\"btn_link\">기업사이트</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"link\">\n");
      out.write("\t\t\t<a href=\"/mbrand/main/main.do\" class=\"btn_link01\">브랜드사이트</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"allmenu\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn_allmenu\"><span class=\"blind\">전체메뉴</span></button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("#resizable\n");
      out.write("{\n");
      out.write("    border: 0px;\n");
      out.write("    width: 30px;\n");
      out.write("    height: 90px;\n");
      out.write("    z-index: 1000;\n");
      out.write("    right: 20px;\n");
      out.write("    bottom: 8%;    \n");
      out.write("    position:fixed;\n");
      out.write("    background-color: transparent;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<div id=\"resizable\" class=\"ui-widget-content\" style=\"z-index: 1000;\">\n");
      out.write("\t<a href=\"/mcompany/main/main.do\"><img style=\"margin-bottom:5px;\" src=\"/brand/images/icon/m_right_fixed_ico01.png\"></a>\n");
      out.write("\t<a href=\"/mcompany/franchisee/red.do\"><img style=\"margin-bottom:5px;\" src=\"/brand/images/icon/m_right_fixed_ico02.png\"></a>\n");
      out.write("\t<a href=\"/company/franchisee/terms.do\"><img src=\"/brand/images/icon/m_right_fixed_ico03.png\"></a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t<!-- //header -->\n");
      out.write("\n");
      out.write("\t<!-- gnb -->\n");
      out.write("\t");
      out.write("\n");
      out.write("\t<div id=\"gnb\">\n");
      out.write("\t\t<!-- <div class=\"gnb_head\">\n");
      out.write("\t\t\t<div class=\"lang\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li class=\"on\"><a href=\"/mbrand/main/main.do\">KOR</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/meng/main/main.do\" target=\"_self\">ENG</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/mjpn/main/main.do\" target=\"_self\">JPN</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div> -->\n");
      out.write("\t\t<div class=\"gnb_container\">\n");
      out.write("\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t<nav class=\"gnb_menu\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\">Phomein</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gnbs\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/phomein/about.do\">브랜드 소개</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mcompany/franchisee/terms.do\">가맹 상담</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/phomein/phoever.do\">CSR</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/phomein/member_ship.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_01.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_02.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_03.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_04.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/phomein/coupon_01.do\">상품권</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/coupon_02.do\">상품권</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/coupon_03.do\">상품권</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\">Menu</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"ea1 gnbs\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/menu/menu_list.do\">포메인</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/menu/red_menu_list.do\">포메인 레드</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\">Store</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"ea1 gnbs\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--<li><a href=\"/mbrand/store/store_best.do\">2018 모범매장</a></li>-->\n");
      out.write("\t\t\t\t\t\t\t\t<!--<li><a href=\"/mbrand/store/interview.do\">우수매장</a></li>-->\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/store/store_list.do\">매장찾기</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\">Community</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gnbs\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/community/notice/community_list.do\">공지&언론보도</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/community/event/community_list.do\">EVENT</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/community/sns/community_list.do\">SNS</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/community/notice/community_view.do\">공지&언론보도</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/community/event/community_view.do\">EVENT</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/community/sns/community_view.do\">SNS</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\">CS CENTER</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"ea1 gnbs\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/cs_center/cs_terms.do\">고객의 소리</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/cs_center/cs_info.do\">고객의 소리</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\">POLICY</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gnbs\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/etc/terms.do\">이용약관</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/etc/privacy.do\">개인정보취급방침</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/mbrand/etc/email.do\">이메일무단수집거부</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t-->\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- <div class=\"banner\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#none\"><img src=\"../common/images/layout/banner_gnb_1.jpg\" alt=\"BEST MENU 포메인 쌀국수\"></a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<button type=\"button\" class=\"btn_close\">\n");
      out.write("\t\t\t<span class=\"blind\">전체메뉴 닫기</span>\n");
      out.write("\t\t</button>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t$(document).ready(function () {\n");
      out.write("\t\tvar url = $(location).attr(\"pathname\");\n");
      out.write("\t\t$('.gnb_menu ul li').removeClass(\"on\"); // depth01 all active remove\n");
      out.write("\t\t$('.gnbs li').removeClass(\"on\"); // depth02 all active remove\n");
      out.write("\n");
      out.write("\t\t$('.gnbs li a').each(function(index) {\n");
      out.write("\t\t\tif($(this).attr(\"href\") == url){\n");
      out.write("\t\t\t\tvar $text = $(this).text();\n");
      out.write("\t\t\t\t$(this).closest('.gnbs').find(\"li a\").each(function(){\n");
      out.write("\t\t\t\t\tif($text== $(this).text()) {\n");
      out.write("\t\t\t\t\t\t$(this).parent(\"li\").attr(\"class\", \"on\"); // depth02 active\n");
      out.write("\t\t\t\t\t\t$(this).closest('.gnbs').parent(\"li\").attr(\"class\", \"on\"); // depth01 active\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\t<!-- //gnb -->\n");
      out.write("\t<!-- container -->\n");
      out.write("\t<div id=\"container\">\n");
      out.write("\t\t<!-- sub visual -->\n");
      out.write("\t\t<div class=\"sub_visual sv6\">\n");
      out.write("\t\t\t<!--<h3></h3>-->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- 상단비쥬얼 영역\n");
      out.write("\t\t\tPHOMEIN   : class=\"sub_visual sv1\"\n");
      out.write("\t\t\tMENU\t  : class=\"sub_visual sv2\"\n");
      out.write("\t\t\tSTORE \t  : class=\"sub_visual sv3\"\n");
      out.write("\t\t\tCOMMUNITY : class=\"sub_visual sv4\"\n");
      out.write("\t\t\tCS CENTER : class=\"sub_visual sv5\"\n");
      out.write("\t\t\tETC \t  : class=\"sub_visual sv6\"\n");
      out.write("\t\t-->\n");
      out.write("\t\t<!-- //sub visual -->\n");
      out.write("\t\t<!-- lnb -->\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\t<div class=\"lnb\">\n");
      out.write("\t\t<div class=\"dep dep1\">\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"nav-title\"></a>\n");
      out.write("\t\t\t<ul class=\"dep_list\">\n");
      out.write("\t\t\t\t<li id=\"PHOMEIN\"><a href=\"/mbrand/phomein/about.do\">PHOMEIN</a></li>\n");
      out.write("\t\t\t\t<li id=\"MENU\"><a href=\"/mbrand/menu/menu_list.do\">MENU</a></li>\n");
      out.write("\t\t\t\t<li id=\"STORE\"><a href=\"/mbrand/store/store_list.do\">STORE</a></li>\n");
      out.write("\t\t\t\t<li id=\"COMMUNITY\"><a href=\"/mbrand/community/notice/community_list.do\">COMMUNITY</a></li>\n");
      out.write("\t\t\t\t<li id=\"CS CENTER\"><a href=\"/mbrand/cs_center/cs_terms.do\">CS CENTER</a></li>\n");
      out.write("\t\t\t\t<li id=\"POLICY\"><a href=\"/mbrand/etc/terms.do\">POLICY</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"dep dep2\" style=\"display:none;\">\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"nav-title\">PHOMEIN</a>\n");
      out.write("\t\t\t<dd style=\"display:none;\">PHOMEIN</dd>\n");
      out.write("\t\t\t<ul class=\"dep_list\">\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/phomein/about.do\">브랜드 소개</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mcompany/franchisee/terms.do\">가맹 상담</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/phomein/phoever.do\">CSR</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/phomein/member_ship.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_01.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_02.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_03.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/mileage_04.do\">멤버십</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/phomein/coupon_01.do\">상품권</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/coupon_02.do\">상품권</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/phomein/coupon_03.do\">상품권</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"dep dep2\" style=\"display:none;\">\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"nav-title\">MENU</a>\n");
      out.write("\t\t\t<dd style=\"display:none;\">MENU</dd>\n");
      out.write("\t\t\t<ul class=\"dep_list\">\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/menu/menu_list.do\">포메인</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/menu/red_menu_list.do\">포메인 레드</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/menu/menu_view.do\">포메인</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/menu/red_menu_view.do\">포메인 레드</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"dep dep2\" style=\"display:none;\">\n");
      out.write("\t\t\t<a href=\"#none\">STORE</a>\n");
      out.write("\t\t\t<dd style=\"display:none;\">STORE</dd>\n");
      out.write("\t\t\t<ul class=\"dep_list\">\n");
      out.write("\t\t\t\t<!--<li><a href=\"/mbrand/store/store_best.do\">2018 모범매장</a></li>-->\n");
      out.write("\t\t\t\t<!--<li><a href=\"/mbrand/store/interview.do\">우수매장</a></li>-->\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/store/store_list.do\">매장찾기</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"dep dep2\" style=\"display:none;\">\n");
      out.write("\t\t\t<a href=\"#none\">COMMUNITY</a>\n");
      out.write("\t\t\t<dd style=\"display:none;\">COMMUNITY</dd>\n");
      out.write("\t\t\t<ul class=\"dep_list\">\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/community/notice/community_list.do\">공지&언론보도</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/community/event/community_list.do\">EVENT</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/community/sns/community_list.do\">SNS</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/community/notice/community_view.do\">공지&언론보도</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/community/event/community_view.do\">EVENT</a></li>\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/community/sns/community_view.do\">SNS</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"dep dep2\" style=\"display:none;\">\n");
      out.write("\t\t\t<a href=\"#none\">CS CENTER</a>\n");
      out.write("\t\t\t<dd style=\"display:none;\">CS CENTER</dd>\n");
      out.write("\t\t\t<ul class=\"dep_list\">\n");
      out.write("\t\t\t\t<li style=\"display:none;\"><a href=\"/mbrand/cs_center/cs_terms.do\">고객의 소리</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/cs_center/cs_info.do\">고객의 소리</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"dep dep2\" style=\"display:none;\">\n");
      out.write("\t\t\t<a href=\"#none\">POLICY</a>\n");
      out.write("\t\t\t<dd style=\"display:none;\">POLICY</dd>\n");
      out.write("\t\t\t<ul class=\"dep_list\">\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/etc/terms.do\">이용약관</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/etc/privacy.do\">개인정보취급방침</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"/mbrand/etc/email.do\">이메일무단수집거부</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t$(document).ready(function () {\n");
      out.write("\t\tvar url = $(location).attr(\"pathname\");\n");
      out.write("\t\t$(\".dep2 ul li a\").each(function(index) {\n");
      out.write("\t\t\tif($(this).attr(\"href\") == url){\n");
      out.write("\t\t\t\t$(this).parent(\"li\").attr(\"class\", \"actived\"); // depth02 active\n");
      out.write("\t\t\t\t$(this).closest(\".dep2\").show(); // depth02 show\n");
      out.write("\t\t\t\tvar aId = $(this).closest(\".dep2\").children('a').text();\n");
      out.write("\t\t\t\t$(\"#\"+aId).attr(\"class\", \"actived\"); // depth01 active\n");
      out.write("\t\t\t\t$(\".dep1\").children('a').text(aId); // depth01 text\n");
      out.write("\t\t\t\t$(this).closest(\".dep2\").children('a').text($(this).text()); // depth02 text\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t</script>");
      out.write("\n");
      out.write("\t\t<!-- //lnb -->\n");
      out.write("\t\t<!-- content -->\n");
      out.write("\t\t<div id=\"content\" class=\"policy\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- 타이틀 영역 -->\n");
      out.write(" \t\t\t<div class=\"tit_area\">\n");
      out.write("\t\t\t\t<h4>이용약관</h4>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- //타이틀 영역 -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"policy_cont\">\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제1조 (목적)</h5>\n");
      out.write("\t\t\t\t<p class=\"txt\">이 약관은 (주)데일리킹 포메인이 홈페이지를 통해 제공하는 각종 정보 서비스(이하 \"서비스\")의 이용조건 및 절차에 관한 사항과 기타 필요한 사 항을 규정함을 목적으로 합니다.</p>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제2조 (약관의 효력과 개정)</h5>\n");
      out.write("\t\t\t\t<ol class=\"txt r_num\">\n");
      out.write("\t\t\t\t\t<li>① 이 약관은 회원등록 시 이용자의 동의와 함께 효력이 발생합니다.</li>\n");
      out.write("\t\t\t\t\t<li>② (주)데일리킹 포메인은 정보 운영의 변경 및 기타 사유로 회원약관을 개정할 수 있으며 개정된 약관은 인터넷서비스 화면에 게재하거나 기타 다른 방법으로 이용자에게 공지함으로써 효력을 발생합니다.</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제3조 (약관외 준칙)</h5>\n");
      out.write("\t\t\t\t<p class=\"txt\">이 약관에 명시되지 않은 사항은 관련법령에 규정되어 있는 경우 그 규정에 따릅니다.</p>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제4조 (용어의 정의)</h5>\n");
      out.write("\t\t\t\t<p class=\"txt\">이 약관에서 사용하는 용어의 정의는 다음 각 호와 같습니다.</p>\n");
      out.write("\t\t\t\t<ol class=\"txt\">\n");
      out.write("\t\t\t\t\t<li>1. 회원 : 회원서비스의 이용을 신청하고 (주)데일리킹 포메인이 승낙하여 회원ID를 발급받은 자.</li>\n");
      out.write("\t\t\t\t\t<li>2. 회원ID : 이용자 식별과 서비스이용을 위하여 이용자가 선정하고 (주)데일리킹 포메인이 부여하는 영문자와 숫자의 조합.</li>\n");
      out.write("\t\t\t\t\t<li>3. 비밀번호 : 이용자와 회원ID가 일치하는 지를 확인하고 통신상의 자신의 비밀번호를 위하여 이용자 자신이 선정한 영문자와 숫자의 조합.</li>\n");
      out.write("\t\t\t\t\t<li>4. 해지 : (주)데일리킹 포메인 또는 이용자가 서비스 개통 후에 그 이용계약을 종료시키는 의사표시.</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제5조 (정보서비스 회원등록의 성립)</h5>\n");
      out.write("\t\t\t\t<ol class=\"txt r_num\">\n");
      out.write("\t\t\t\t\t<li>① 회원등록은 이용자의 이용 신청에 대한 (주)데일리킹 포메인의 이용 승낙과 이용자의 약관내용에 대한 동의로 성립됩니다.</li>\n");
      out.write("\t\t\t\t\t<li>② 회원으로 등록하여 서비스를 이용하고자 하는 자는 (주)데일리킹 포메인에서 요구하는 개인 신상 정보를 제공해야 합니다.</li>\n");
      out.write("\t\t\t\t\t<li>③ 회원등록 신청을 (주)데일리킹 포메인이 승인한 경우, (주)데일리킹 포메인은 회원 ID와 비밀번호, 정보안내등 필요한 사항을 회원에게 통지합니다.</li>\n");
      out.write("\t\t\t\t\t<li>④ (주)데일리킹 포메인은 다음 각 호에 해당하는 경우 회원등록 신청을 승인하지 않을 수 있습니다.\n");
      out.write("\t\t\t\t\t\t<ol class=\"txt\">\n");
      out.write("\t\t\t\t\t\t\t<li>1. 다른 사람의 명의를 사용하여 신청하였을 때</li>\n");
      out.write("\t\t\t\t\t\t\t<li>2. 본인의 실명으로 신청하지 않았을 때</li>\n");
      out.write("\t\t\t\t\t\t\t<li>3. 회원등록 신청서의 내용을 허위로 기재하였을 때</li>\n");
      out.write("\t\t\t\t\t\t\t<li>4. 사회의 안녕과 질서 혹은 미풍양속을 저해할 목적으로 신청하였을 때</li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제6조 ((주)데일리킹 포메인의 의무)</h5>\n");
      out.write("\t\t\t\t<ol class=\"txt r_num\">\n");
      out.write("\t\t\t\t\t<li>① (주)데일리킹 포메인는 업무상 또는 기술상 특별한 지장이 없는 한 계속적, 안정적(연중무휴,1일 24시간)으로 서비스를 제공할 의무가 있습니다.<br>단, 천재지변 및 시스템 정기점검 등 (주)데일리킹 포메인이 필요한 경우, 회원에게 사전 통지한 후, 제한할 수 있습니다.</li>\n");
      out.write("\t\t\t\t\t<li>② (주)데일리킹 포메인은 특별한 사정이 없는 한 회원등록 개시일에 회원이 서비스를 이용할 수있도록 합니다.</li>\n");
      out.write("\t\t\t\t\t<li>③ (주)데일리킹 포메인은 회원으로부터 게시판 등에 의해 제기되는 의견에 대해서는 적절한 절차를 거처 처리하며, 처리시 일정 기간이 소요될 경우 회원에게 그 사유와 처리 일정 알려주어야 합니다.</li>\n");
      out.write("\t\t\t\t\t<li>④ (주)데일리킹 포메인은 회원의 정보를 철저히 보안 유지하며, 양질의 서비스를 운영하거나 개선하는 데에만 사용하고, 이외의 다른 목적으로 타 기관 및 개인에게 양도하지 않습니다.<br>단, 형사상 목적이나 공적인 목적으로 공공기관의 요청이 있는 경우, 특정개인을 식별 할 수 없는 통계자료, 학술연구 등의 목적일 때에는 예외로 합니다.</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제7조 (회원의 의무)</h5>\n");
      out.write("\t\t\t\t<ol class=\"txt r_num\">\n");
      out.write("\t\t\t\t\t<li>① ID와 비밀번호에 관한 모든 관리의 책임은 회원에게 있습니다.</li>\n");
      out.write("\t\t\t\t\t<li>② 회원은 서비스의 일부로 보내지는 (주)데일리킹 포메인의 전자우편을 받는 것에 동의합니다.</li>\n");
      out.write("\t\t\t\t\t<li>③ 자신의 ID가 부정하게 사용된 경우, 회원은 반드시 (주)데일리킹 포메인에 그 사실을 통보해야 합니다.</li>\n");
      out.write("\t\t\t\t\t<li>④ 회원은 이 약관 및 관계 법령에서 규정한 사항을 준수하여야 합니다.</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제8조 (회원등록 해지 및 이용 제한)</h5>\n");
      out.write("\t\t\t\t<ol class=\"txt r_num\">\n");
      out.write("\t\t\t\t\t<li>① 회원등록을 해지하고자 하는 때에는 회원 본인이 직접 해지하고, 게시판 등에 제기한 본인의 의견 및 답변 등을 제외한 본인의 회원정보를 삭제할 수 있습니다.</li>\n");
      out.write("\t\t\t\t\t<li>② (주)데일리킹 포메인은 가입기록과의 일치여부를 확인한 후 회원등록을 자동으로 해지하고, 메일로 통보하며, 한번 해지된 ID는 기존 사용자라도 사용할 수 없습니다.</li>\n");
      out.write("\t\t\t\t\t<li>③ (주)데일리킹 포메인은 회원이 다음 각 호의 사항에 해당하는 행위를 하였을 경우, 사전 통지 없이 이용 계약을 해지하거나 또는 기간을 정하여 서비스 이용을 중지할 수 있습니다.\n");
      out.write("\t\t\t\t\t\t<ol class=\"txt\">\n");
      out.write("\t\t\t\t\t\t\t<li>1. 공공 질서 및 미풍 양속에 반하는 경우</li>\n");
      out.write("\t\t\t\t\t\t\t<li>2. 범죄적 행위에 관련되는 경우</li>\n");
      out.write("\t\t\t\t\t\t\t<li>3. 국익 또는 사회적 공익을 저해할 목적으로 서비스 이용을 계획 또는 실행할 경우</li>\n");
      out.write("\t\t\t\t\t\t\t<li>4. 타인의 ID 및 비밀번호를 도용한 경우</li>\n");
      out.write("\t\t\t\t\t\t\t<li>5. 타인의 명예를 손상시키거나 불이익을 주는 경우</li>\n");
      out.write("\t\t\t\t\t\t\t<li>6. 같은 사용자가 다른 ID로 이중 등록을 한 경우</li>\n");
      out.write("\t\t\t\t\t\t\t<li>7. 서비스에 위해를 가하는 등 건전한 이용을 저해하는 경우</li>\n");
      out.write("\t\t\t\t\t\t\t<li>8. 기타 관련 법령이나 (주)데일리킹 포메인가 정한 이용조건에 위배되는 경우</li>\n");
      out.write("\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>④ (주)데일리킹 포메인은 이용 제한을 하고자 하는 경우에는 그 사유, 일시 및 기간을 정하여 서면 또는 전화 등의 방법을 이용하여 해당 회원 또는 대리인에게 통지합니다. <br>단, (주)데일리킹 포메인이 긴급하게 이용을 중지해야 할 필요가 있다고 인정하는 경우에는 위 사항의 과정 없이 서비스 이용을 제한 할 수 있습니다.\n");
      out.write("\t\t\t\t\t<li>⑤ 제7조 4항의 규정에 의하여 서비스 이용중지를 통지 받은 회원 또는 그 대리인은 이용중지에 대하여 이의가 있을 경우 이의신청을 할 수 있습니다.</li>\n");
      out.write("\t\t\t\t\t<li>⑥ (주)데일리킹 포메인은 이용중지 기간 중에 그 이용중지 사유가 해소된 것이 확인된 경우에 한하여 이용중지 조치를 해제할 수 있습니다.</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제9조 (회원의 게시내용 관리)</h5>\n");
      out.write("\t\t\t\t<p class=\"txt\">(주)데일리킹 포메인은 서비스에 회원이 게시하거나 등록한 내용물이 다음 각 호의 사항에 해당된다고 판단되는 경우에 사전 통지 없이 삭제할 수 있습니다.</p>\n");
      out.write("\t\t\t\t<ol class=\"txt\">\n");
      out.write("\t\t\t\t\t<li>1. 타인을 비방하거나 중상모략으로 개인 및 단체의 명예를 손상시키는 내용인 경우</li>\n");
      out.write("\t\t\t\t\t<li>2. 공공질서 및 미풍양속에 위반되는 내용인 경우</li>\n");
      out.write("\t\t\t\t\t<li>3. 범죄적 행위에 부합된다고 인정되는 내용인 경우</li>\n");
      out.write("\t\t\t\t\t<li>4. 타인의 저작권 등 기타의 권리를 침해하는 내용인 경우</li>\n");
      out.write("\t\t\t\t\t<li>5. 각 정보의 등록 대상이 아닌 경우</li>\n");
      out.write("\t\t\t\t\t<li>6. 기타 관계 법령이나 (주)데일리킹 포메인에서 정한 규정에 위배되는 내용인 경우</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">제10조 (게시물 관리 및 저작권)</h5>\n");
      out.write("\t\t\t\t<ol class=\"txt r_num\">\n");
      out.write("\t\t\t\t\t<li>① 회원이 서비스 내에 등록한 게시물의 저작권은 회원과 (주)데일리킹 포메인이 공동 소유합니다.</li>\n");
      out.write("\t\t\t\t\t<li>② 회원은 (주)데일리킹 포메인에서 허용한 경우를 제외하고는 서비스의 내용을 이용하여 영업 활동을 하거나 허용되지 않은 영업에 사용하여서는 안됩니다.</li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t\t<h5 class=\"tit\">부칙</h5>\n");
      out.write("\t\t\t\t<p class=\"txt\">본 약관은 2012년 06월 22일부터 그 효력이 발생합니다.</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- //content -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- //container -->\n");
      out.write("\n");
      out.write("\t<!-- footer -->\n");
      out.write("\t");
      out.write("\n");
      out.write("\t<footer id=\"footer\">\n");
      out.write("\t\t<!-- family-site -->\n");
      out.write("\t\t<!-- <div class=\"family-site\">\n");
      out.write("\t\t\t<a href=\"#\">FAMILY SITE</a>\n");
      out.write("\t\t\t<div class=\"list\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 1</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 2</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사이트 3</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div> -->\n");
      out.write("\t\t<!-- //family-site -->\n");
      out.write("\t\t<ul class=\"foot_menu\">\n");
      out.write("\t\t\t<li><a href=\"/mbrand/cs_center/cs_terms.do\">고객의 소리</a></li>\n");
      out.write("\t\t\t<li><a href=\"/mbrand/phomein/mileage_01.do\">마일리지 조회</a></li>\n");
      out.write("\t\t\t<li><a href=\"/mbrand/phomein/coupon_01.do\">상품권 구매</a></li>\n");
      out.write("\t\t\t<li><a href=\"http://www.phomein.com/store/login.do\">인트라넷</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<p class=\"copyright\">\n");
      out.write("\t\t\t가맹문의  대표번호: 1899-2422(연결 1번)<br>\n");
      out.write("\t\t\t직통번호: 031-780-1500 | 이메일: help@phomein.com<br>\n");
      out.write("\t\t\tCOPYRIGHT© DAILYKING INC. ALL RIGHT RESERVED.\n");
      out.write("\t\t</p>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("<!-- Global site tag (gtag.js) - Google Analytics -->\n");
      out.write("<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-135650389-1\"></script>\n");
      out.write("<script>\n");
      out.write("  window.dataLayer = window.dataLayer || [];\n");
      out.write("  function gtag(){dataLayer.push(arguments);}\n");
      out.write("  gtag('js', new Date());\n");
      out.write("\n");
      out.write("  gtag('config', 'UA-135650389-1');\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("var host = window.location.host;\n");
      out.write("var total_url = window.location.href;\n");
      out.write("if ( host.indexOf(\".com\") > 0 ){\n");
      out.write("}else{\n");
      out.write("\t if ( host.indexOf(\"www.\") > 0 ) {\n");
      out.write("\t}else{\n");
      out.write("\t\tif( domain.indexOf(\"dev\") < 0 ){\n");
      out.write("\t\t\tlocation.href=\"http://www.phomein.com\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\t<!-- //footer -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- //wrap -->\n");
      out.write("\n");
      out.write("<script src=\"../common/js/jquery-1.12.4.min.js\"></script>\n");
      out.write("<script src=\"../common/js/swiper.min.js\"></script>\n");
      out.write("<script src=\"../common/js/common.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("domain");
      // /WEB-INF/jsp/include/declare.jspf(12,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("requrl");
      // /WEB-INF/jsp/include/declare.jspf(13,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.requestURI}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
